name: finalproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/design_logo.png
    - assets/images/concert.jpg
    - assets/images/theater.jpg
    - assets/images/gallery.jpg
    - assets/images/stadium.jpg
    - assets/images/jazz.jpg
    - assets/images/balloon.jpg